package edu.kpi.io8322.sysprog.lab.syntax;

public enum NodeType {
    NONE, EXPR, EXPR_CONST, EXPR_CONSTINT, EXPR_ID, EXPR_IDFUNCTION, EXPR_IDVAR,
    STMT, STMT_RETURN, STMT_BLOCK, STMT_FUNCTION, STMT_PROGRAM
}
