package edu.kpi.io8322.sysprog.lab.syntax;

public enum NodeType {
    NONE, EXPR, EXPR_CONST, EXPR_CONSTINT, EXPR_ID, EXPR_IDFUNCTION, EXPR_IDVAR,
    STMT, STMT_RETURN, STMT_BLOCK, STMT_FUNCTION, STMT_PROGRAM,
    EXPR_UNARY, EXPR_BINARY, EXPR_UNARYNOT, EXPR_BINARYPLUS,
    EXPR_BINARYMINUS, EXPR_BINARYLESS, STMT_SET, STMT_SEQ, EXPR_GETVARVALUE,
    EXPR_TERNARY
}
